title: What to watch next?
author: Anthony Jaimes
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hello, are you not sure what anime to watch next? Or simply want to talk about a show?
  Well this is the website for you!

# social links
twitter_username: target # DO NOT include the @ character, or else the build will fail!
github_username:  DonutBxy # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
